CREATE OR REPLACE PROCEDURE SP_REMOVE_TABLE_CONSTRAINTS(V_TABLE_NAME IN VARCHAR2,
                                                        V_OWNER IN VARCHAR2)
AS
CURSOR C1 IS
   SELECT AC.CONSTRAINT_NAME
   FROM ALL_CONSTRAINTS AC
   WHERE AC.TABLE_NAME = UPPER(V_TABLE_NAME)
     AND AC.OWNER = UPPER(V_OWNER);
BEGIN
  FOR REC IN C1
   LOOP
     BEGIN
       EXECUTE IMMEDIATE 'ALTER TABLE ' || V_OWNER ||'.'|| V_TABLE_NAME || ' DROP CONSTRAINT '  || REC.CONSTRAINT_NAME;
     END;
   END LOOP;

END SP_REMOVE_TABLE_CONSTRAINTS;
/
